version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: plasmic-db
    restart: always
    environment:
      POSTGRES_USER: wab
      POSTGRES_PASSWORD: plasmic
      POSTGRES_DB: wab
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wab -d wab"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plasmic-net

  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    restart: always
    environment:
      VERDACCIO_PORT: "4873"
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_conf:/verdaccio/conf
    networks:
      - plasmic-net

  plasmic-app:
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        DB_HOST_ARG: db
        DB_USER_ARG: wab
        DB_PASSWORD_ARG: plasmic
        DB_NAME_ARG: wab
        DB_PORT_ARG: 5432
    container_name: plasmic-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      verdaccio:
        condition: service_started
    environment:
      NODE_ENV: development
      PGHOST: db
      PGPORT: 5432
      PGUSER: wab
      PGPASSWORD: plasmic
      PGDATABASE: wab
      SESSION_SECRET: "REPLACE_WITH_REAL_SECRET"
    ports:
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
    volumes:
      - app_logs:/app/logs
    networks:
      - plasmic-net

networks:
  plasmic-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  verdaccio_storage:
    driver: local
  verdaccio_conf:
    driver: local
  app_logs:
    driver: local
