version: "3.8"

services:
  # PostgreSQL database
  plasmic-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wab
      POSTGRES_PASSWORD: SEKRET
      POSTGRES_DB: wab
    ports:
      - "5432:5432"
    volumes:
      # Remove the old postgres_data volume if you want POSTGRES_USER/DB to apply
      - postgres_data:/var/lib/postgresql/data
      # Init script to ensure wab user/db exist even if volume is reused
      - ./platform/wab/tools/docker-dev/db-setup.bash:/docker-entrypoint-initdb.d/db-setup.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wab -d wab"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Plasmic WAB (Web App Builder)
  plasmic-wab:
    build:
      context: .
      dockerfile: ./platform/wab/tools/docker-dev/Dockerfile.dev.aio
    command: >
      sh -c "
      jq '(.host = \"plasmic-db\") | (.username = \"wab\") | (.password //= \"SEKRET\") | (.database = \"wab\")' ormconfig.json > tmp.json &&
      mv tmp.json ormconfig.json &&
      yarn typeorm migration:run &&
      yarn seed &&
      cd /plasmic &&
      yarn dev
      "
    volumes:
      - .:/plasmic
      - plasmic_node_modules:/plasmic/node_modules
      - plasmic_wab_node_modules:/plasmic/platform/wab/node_modules
      - plasmic_sub_node_modules:/plasmic/platform/sub/node_modules
      - plasmic_canvas_node_modules:/plasmic/platform/canvas-packages/node_modules
      - plasmic_live_frame_node_modules:/plasmic/platform/live-frame/node_modules
      - plasmic_react_web_bundle_node_modules:/plasmic/platform/react-web-bundle/node_modules
      - plasmic_loader_bundle_env_node_modules:/plasmic/platform/loader-bundle-env/node_modules
      - plasmic_loader_html_hydrate_node_modules:/plasmic/platform/loader-html-hydrate/node_modules
      - plasmic_public:/plasmic/platform/wab/public
      - plasmic_wab_client:/plasmic/platform/wab/src/wab/client
      - plasmic_wab_gen:/plasmic/platform/wab/src/wab/gen
      - plasmic_wab_shared_model:/plasmic/platform/wab/src/wab/shared/model
      - plasmic_generated_styles:/plasmic/platform/wab/src/wab/styles
      - plasmic_playwright_cache:/home/plasmic/.cache/ms-playwright
    ports:
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "9229:9229"
    depends_on:
      plasmic-db:
        condition: service_healthy
    environment:
      DATABASE_URI: postgres://wab:SEKRET@plasmic-db:5432/wab
      WAB_DBNAME: wab
      WAB_DBPASSWORD: SEKRET
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  plasmic_node_modules:
  plasmic_wab_node_modules:
  plasmic_sub_node_modules:
  plasmic_canvas_node_modules:
  plasmic_live_frame_node_modules:
  plasmic_react_web_bundle_node_modules:
  plasmic_loader_bundle_env_node_modules:
  plasmic_loader_html_hydrate_node_modules:
  plasmic_playwright_cache:
  plasmic_generated_styles:
  plasmic_public:
  plasmic_wab_client:
  plasmic_wab_gen:
  plasmic_wab_shared_model:
